### ISSUE TITLE
Blue light turns violett in Camera View

### ISSUE THREAD

**Issue by davidAnPrintell** [SceneView/sceneform-android#295] opened 2022-01-28 13:40 UTC
Hi!

I faced some unexpected color behavior, if there is a blue light source indoor.
Im worried that there will be other color grading issues.

## Expected Behavior

The camera view renders the expected color, like other AR cameras or the native camera.

<img src="https://user-images.githubusercontent.com/96430005/151553580-a6793691-60bf-4e94-92b1-13ed4e7b4a8a.jpg" width="300">

## Current Behavior
The camera view renders a violet color.
<img src="https://user-images.githubusercontent.com/96430005/151554396-31147fa5-1355-4d84-9140-ee9cd5a6b687.jpg" width="300">
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run a sample Project (tested with Augmented Images and environment-lights) on an android device ( tested on an Samsung Galaxy S8 and S20).
2. Turn a blue light source on

## Context
Couldnt reproduce the issue with archived Sceneform 1.15.0.   
Expected Behavior Screenshot is the sample AR-Core Augmented Images project (OpenGL Rendering)

Current Behavior testet with
* SDK version: Android-Version 12

**Comment by ThomasGorisse** [comment] 2022-01-28 13:54
Hi,

Can you try to [disable light estimation](https://github.com/SceneView/sceneform-android#environment-lights)?

**Comment by davidAnPrintell** [comment] 2022-01-28 14:00
Thanks for your quick reply.
I also had this issue with all the available configs in the sample light estimation app.

My Configs: 
```kotlin
config.updateMode = Config.UpdateMode.LATEST_CAMERA_IMAGE
config.focusMode = Config.FocusMode.AUTO
config.planeFindingMode = Config.PlaneFindingMode.DISABLED
config.instantPlacementMode = Config.InstantPlacementMode.DISABLED
config.augmentedFaceMode = Config.AugmentedFaceMode.DISABLED
config.lightEstimationMode = Config.LightEstimationMode.DISABLED
config.augmentedImageDatabase = imageDatabase
session.configure(config)
arSceneView?.setSession(session)

**Comment by ThomasGorisse** [comment] 2022-01-28 14:05
Please also call `arSceneView.lightEstimationConfig = LightEstimationConfig.DISABLED`

**Comment by davidAnPrintell** [comment] 2022-01-28 18:59
To better reproduce the issue, i just filmed some blue images from google images. Result:
<div style="display: flex;
  flex-direction: row;  justify-content: space-between;">

<img src="https://user-images.githubusercontent.com/96430005/151603983-fc41ea79-5eab-44bf-9b1b-b48162b9a981.jpg" width=250>

<img src="https://user-images.githubusercontent.com/96430005/151603986-09f9d82a-85a1-4053-aa9e-04b4240fb482.jpg" width=250>
<img src="https://user-images.githubusercontent.com/96430005/151603994-49d83541-1147-46f4-a8b8-8bf2d7120c0a.jpg" width=250>
</div>

First Img is my app with following configs:

```kotlin
                    config.updateMode = Config.UpdateMode.LATEST_CAMERA_IMAGE
                    config.focusMode = Config.FocusMode.AUTO;
                    config.planeFindingMode = Config.PlaneFindingMode.DISABLED
                    config.augmentedImageDatabase = imageDatabase
                    session.configure(config)
                    arSceneView?.lightEstimationConfig = LightEstimationConfig.DISABLED
                    arSceneView?.setSession(session)
```
Second Img is https://github.com/SceneView/sceneform-android/tree/master/samples/augmented-images

Thrid Img is https://github.com/google-ar/arcore-android-sdk/tree/master/samples/augmented_image_java

**Comment by ThomasGorisse** [comment] 2022-01-28 19:03
@RGregat Do you think it could be a Filmic color mode issue?

**Comment by grassydragon** [comment] 2022-01-28 21:27
Since the `inverseTonemapSRGB` function is used in the camera material the camera image can be also affected by the color issues. According to Romain, the inverse tonemapping operation should be exact for the Filmic tonemapping. However, something could have changed in Filament or Sceneform because the problem with the `ViewRenderable` color has been reported recently: https://github.com/SceneView/sceneform-android/issues/252

**Comment by ThomasGorisse** [comment] 2022-01-28 21:57
@davidAnPrintell Would you mind creating an issue on the [Filament repo](https://github.com/google/filament) discussion section and linking/mentioning this issue?

**Comment by ThomasGorisse** [comment] 2022-01-28 22:00
BTW, thanks for your detailed issue.

**Comment by davidAnPrintell** [comment] 2022-01-28 22:42
Link for Diskussion: https://github.com/google/filament/discussions/5136

**Comment by romainguy** [comment] 2022-01-28 23:20
It's a known side effect of inverse tone mapping. You are seeing a hue shift due to out of gamut colors. We already have an open bug for this and it's not entirely trivial to fix. In the meantime make sure you are using the FILMIC tone mapper.

**Comment by ThomasGorisse** [comment] 2022-01-29 07:57
Thanks.

I confirm that the [workaround](https://github.com/google/filament/issues/3909#issuecomment-877241573) is still applied here:
https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/SceneView.java#L386

**Comment by grassydragon** [comment] 2022-01-29 07:59
If I use the deprecated `toneMapping(ColorGrading.ToneMapping.FILMIC)` here, the colors are rendered as expected:
https://github.com/SceneView/sceneform-android/blob/5b5ae1f511a032d224b1678eb4b7befdc0e5bc11/core/src/main/java/com/google/ar/sceneform/SceneView.java#L391

**Comment by ThomasGorisse** [comment] 2022-01-29 08:03
@davidAnPrintell Can you confirm that you are actually using the last version?

**Comment by romainguy** [comment] 2022-01-29 08:12
Yeah I need to find a good way to offer inverse tone mapping based on the selected tone mapper in ColorGrading.

**Comment by ThomasGorisse** [comment] 2022-01-29 08:21
@davidAnPrintell Can you try calling this?
```kotlin
arSceneView.renderer!!.filamentView.colorGrading =
            ColorGrading.Builder().toneMapping(ColorGrading.ToneMapping.FILMIC)
                .build(EngineInstance.getEngine().filamentEngine)
```

**Comment by davidAnPrintell** [comment] 2022-01-29 08:31
Thanks a lot. Its solves the issue

**Comment by davidAnPrintell** [comment] 2022-01-29 13:42
I'll close this issue, since its a known filament bug.
Thanks for the help

**Comment by ThomasGorisse** [comment] 2022-02-09 17:27
@grassydragon @RGregat Did we merged it?

**Comment by grassydragon** [comment] 2022-02-09 18:18
> @grassydragon @RGregat Did we merged it?

No, should we merge it and wait for the related Filament issue to be resolved?

**Comment by romainguy** [comment] 2022-02-09 18:21
Note that `toneMapping(ColorGrading.ToneMapping.FILMIC)` will not go anywhere. It's marked deprecated because I'd like to move our users to " better" tone mappers, but we won't remove it from our APIs. You can safely use it.

Ideally I'd like everyone to use the generic tone mapper (terrible name, great tone mapper) with luminance scaling turned on.

**Comment by ThomasGorisse** [comment] 2022-02-09 18:53
I'm correct?
```kotlin
renderer.getFilamentView().setColorGrading(
        new ColorGrading
                .Builder()
                .toneMapper(new ToneMapper.Generic())
                .luminanceScaling(false)
                .build(EngineInstance.getEngine().getFilamentEngine())
);
```

**Comment by ThomasGorisse** [comment] 2022-02-09 19:00
> Except you have luminance scaling off :p But luminance scaling would need to be invertible, that's another story.

Sorry I'm tired. Answer edited

**Comment by ThomasGorisse** [comment] 2022-02-09 19:05
So we can't use the generic tone mapper even with `luminanceScaling(true)` to solve the blue issue?

**Comment by romainguy** [comment] 2022-02-09 19:06
The problem is how inverseTonemap() works. It was designed for FILMIC, and will only be somewhat of an approximation with other tone mappers.

**Comment by ThomasGorisse** [comment] 2022-02-09 19:14
@grassydragon I'm not good enough in fragment shader. Do you think there could be any other way than using the inverse tonemap for the camera stream here:
https://github.com/SceneView/sceneform-android/blob/03409ab11f2923cc7e4e2f622758f9d5e3288c6b/core/assets-sources/materials/sceneform_camera_material.mat#L23

**Comment by grassydragon** [comment] 2022-02-09 19:18
I think only if we use the linear tone mapper or there is a way to disable the tone mapping for particular renderables (the camera stream and view renderables).

**Comment by romainguy** [comment] 2022-02-09 19:19
Just use `FILMIC` and `inverseTonemapSRGB()` :)

**Comment by ThomasGorisse** [comment] 2022-02-09 19:35
@grassydragon Can you PR it?
// Change the ToneMapper to FILMIC to avoid some over saturated
// colors, for example material orange 500.
```java
renderer.getFilamentView().setColorGrading(
        new ColorGrading
                .Builder()
                .toneMapping(ColorGrading.ToneMapping.FILMIC)
                .build(EngineInstance.getEngine().getFilamentEngine())
);
```

**Comment by ThomasGorisse** [comment] 2022-02-09 19:50
Surely not related but this blue issue made me thought about some color issues I had during lights estimation work.
I always though that it was due to ARCore more recognizing blue than other colors but could it be related to some Filmic color accentuation differences?
|   |   |   |
| - | - | - |
| ![Screenshot_20210830-222747](https://user-images.githubusercontent.com/6597529/153277482-a6916e3d-f404-4c78-8c4a-8a9c86c5fddb.png) | ![Screenshot_20210830-223026](https://user-images.githubusercontent.com/6597529/153278279-a0863d70-4779-4d9d-a3cb-ae2ad048d2ec.jpg) | ![Screenshot_20210830-222818](https://user-images.githubusercontent.com/6597529/153277487-adb05db5-0951-44e6-8d07-c49e33f2d8d1.png) |
| ![Screenshot_20210830-222016](https://user-images.githubusercontent.com/6597529/153278375-7a7d2e3d-9d6f-4b90-8086-48156b65385b.jpg) | ![Screenshot_20210830-223223](https://user-images.githubusercontent.com/6597529/153278413-c3732595-080b-499a-90a2-20d7b85dc56b.jpg) | ![Screenshot_20210830-221800](https://user-images.githubusercontent.com/6597529/153278555-59f3a1ab-e416-4495-a05e-b9dd5caf48de.jpg) |

As you can see, red and green are less present in the reflections than other colors (Maybe it's only main light estimation issue but I try my luck)

**Comment by romainguy** [comment] 2022-02-09 20:02
Seems like a light estimation issue. Tone mapping would not be responsible for removing green from the lighting.

**Comment by ThomasGorisse** [comment] 2022-02-09 20:13
I just made the test again and confirm it's an ARCore "issue".
@devbridie, any idea why would red and green are less recognized?
On the right column, the ARCore estimated environment reflections applied to the Skybox. Main light color also applied.
|  |  |
| - | - |
| ![Screenshot_20220209-205940](https://user-images.githubusercontent.com/6597529/153282076-91f72624-56cb-4dce-a728-4df1cb4fc58e.png) | ![Screenshot_20220209-205945](https://user-images.githubusercontent.com/6597529/153282091-dc48ebae-9453-46b1-9b54-f17685c0206d.png) |
| ![Screenshot_20220209-210029](https://user-images.githubusercontent.com/6597529/153282207-763090cc-e636-4f5f-b0df-7cadf08847e2.png) | ![Screenshot_20220209-210018](https://user-images.githubusercontent.com/6597529/153282231-136fbd45-3309-47c8-9026-9c3178da06e9.png)
| ![Screenshot_20220209-210230](https://user-images.githubusercontent.com/6597529/153282333-1d08dae3-38bb-4a5f-8220-28a98eb2b6fc.png) | ![Screenshot_20220209-210145](https://user-images.githubusercontent.com/6597529/153282384-dd036405-df20-4b57-9877-1b0276052b67.png) |

**Closed** 2022-02-10 19:26 UTC
