### ISSUE TITLE
Blinking gray screen on the first run

### ISSUE THREAD

**Issue by denisk20** [SceneView/sceneform-android#266] opened 2022-01-01 16:10 UTC
Hi,
Thank you for the hard work on this. 
I'm migrating my app, which uses front camera and Augmented Faces, from google sceneform 1.17.1. After switching I see a blinking gray area (which reacts to the front camera) where my ArFragment is. This happens only on the first run, after Camera permission is granted. If I re-launch the app (with permissions granted) the issue goes away. If I manually revoke the Camera permission the issue re-appears.
The issue never happens with sceneform 1.17.1 + arcore 1.29.0. The issue only happens with the front camera.
In the logs I see tons of errors:

`session.cc:2517] Invalid ray produced by view data!`

A sample branch for this issue (just launch the project in Android Studio, the issue appears instantly after granting Camera permission)
https://github.com/denisk20/diopter-calc/tree/sceneview-updated

[This](https://github.com/denisk20/diopter-calc/blob/sceneview-updated/app/src/main/java/org/endmyopia/calc/measure/FaceArFragment.kt#L79) is the place where I configure my ArFragment.

Any hint on why this happens is highly appreciated.

![IMG_4918](https://user-images.githubusercontent.com/3080318/147854294-c1ae1b6e-eb74-4094-ae8d-961a4f8c8d7c.gif)

**Comment by grassydragon** [comment] 2022-01-02 09:22
Hi @denisk20!
This is a known issue not only in Sceneform but also in the new Sceneview library and with the rear camera too. From our experience, it happens when you launch the application through adb and the screen is locked. You can try revoking the permissions and launching the application manually

**Comment by ThomasGorisse** [comment] 2022-01-02 09:51
@grassydragon is right.
We didn't managed to solved it yet but you must have in mind that's it's only a developer mode bug since a case where the app is launched while the phone is locked may not happen outside of adb using.

**Comment by denisk20** [comment] 2022-01-02 12:45
Doesn't seem to be limited to a locked phone phone for me. If I revoke the permission and open the app, the issue persists.
![20220102_143849](https://user-images.githubusercontent.com/3080318/147876053-7314f9a0-668f-42de-b294-0c869e9716f9.gif)

**Comment by grassydragon** [comment] 2022-01-02 14:46
I've successfully reproduced this behavior. I hope that we can understand what causes it based on your application.

**Comment by grassydragon** [comment] 2022-01-03 07:59
I've found a way to reproduce this behavior on our Augmented Faces sample. We just need to disable the fullscreen mode:
``` Java
Bundle args = new Bundle();
args.putBoolean(BaseArFragment.ARGUMENT_FULLSCREEN, false);

if (savedInstanceState == null) {
    if (Sceneform.isSupported(this)) {
        getSupportFragmentManager().beginTransaction()
                .add(R.id.arFragment, ArFrontFacingFragment.class, args)
                .commit();
    }
}
```
I think the problem is related to the order in which the ARCore `Session` methods including `setDisplayGeometry` are called.

**Comment by grassydragon** [comment] 2022-01-03 08:07
And it's true! If I change the code so that `Session.setDisplayGeometry` is called after `Session.resume`, everything works fine :tada:

**Comment by ThomasGorisse** [comment] 2022-01-03 15:00
Also merged in sceneview-android/main: SceneView/sceneview-android@8985f50

**Comment by ThomasGorisse** [comment] 2022-01-03 15:00
Also merged in sceneview-android/dev: SceneView/sceneview-android@e00704e

**Closed** 2022-01-03 14:59 UTC
Labels: bug

**Comment by ThomasGorisse** [comment] 2022-01-03 15:01
New Release?
